# Generated by Django 3.0.5 on 2020-05-02 05:11

import ckeditor.fields
from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Xeber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/azdili', verbose_name='Archive')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/azdili', verbose_name='Cover')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icon/azdili', verbose_name='Icon')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
