# Generated by Django 3.0.5 on 2020-04-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentiq', '0002_mentiq_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentiq',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/mentiq', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='mentiq',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/mentiq', verbose_name='Archive'),
        ),
        migrations.AlterField(
            model_name='mentiq',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icon/mentiq', verbose_name='Icon'),
        ),
    ]
