# Generated by Django 3.0.5 on 2020-04-29 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('published', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField(max_length=250, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created on')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='Updated')),
                ('expiration_date', models.DateTimeField(auto_now_add=True, verbose_name='Experience')),
                ('file', models.FileField(upload_to='upload/file/materials', verbose_name='Archive')),
                ('cover', models.ImageField(upload_to='upload/cover/materials', verbose_name='Cover')),
                ('category', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
