# Generated by Django 3.0.5 on 2020-04-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='category',
            new_name='tags',
        ),
        migrations.RemoveField(
            model_name='material',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='material',
            name='published',
        ),
        migrations.AlterField(
            model_name='material',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='upload/cover/materials', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/file/materials', verbose_name='Archive'),
        ),
    ]
