# Generated by Django 3.0.5 on 2020-04-30 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informatika', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informatika',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='upload/cover/informatika', verbose_name='Cover'),
        ),
        migrations.AlterField(
            model_name='informatika',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='upload/file/informatika', verbose_name='Archive'),
        ),
    ]
